"""Deterministic mock VLM backend.

This is the always-on default and the backend used in automated tests. It is NOT a real
model: it produces a deterministic, honest description derived from the detector-grounding
context (object counts) when available, or a clearly-labelled generic response otherwise.
Timings are measured wall-clock; token counts are word counts. It never invents specific
scene facts beyond what the grounding provides.
"""
from __future__ import annotations

import json
import time
from collections import Counter

from app.core.types import HealthState, VLMResponse
from app.vlm.base import BaseVLMBackend, ImageInput
from app.vlm.structured_output import SceneUnderstanding

_MOCK_NOTE = "mock VLM: deterministic output derived from detector context, not a real model"


def _summarize_grounding(grounding: dict | None) -> tuple[str, list[str]]:
    if not grounding or not grounding.get("detected_objects"):
        return ("The scene could not be grounded with detections; a real VLM is required "
                "for open-ended description."), []
    names = [o["class"] for o in grounding["detected_objects"]]
    counts = Counter(names)
    parts = [f"{n} {name}{'s' if n > 1 else ''}" for name, n in counts.most_common()]
    objects = sorted(counts)
    if not parts:
        return "No objects were detected in the scene.", objects
    listing = ", ".join(parts[:-1]) + (f" and {parts[-1]}" if len(parts) > 1 else parts[0])
    return f"The scene appears to contain {listing}.", objects


class MockVLMBackend(BaseVLMBackend):
    model_id = "mock-vlm"
    runtime = "python"
    execution_location = "pc_local"

    def load(self) -> None:
        self._health = HealthState.READY

    def warmup(self) -> None:
        pass

    def _respond(self, text: str, structured: dict | None, t0: float,
                 warnings: list[str]) -> VLMResponse:
        dt = (time.perf_counter() - t0) * 1000.0
        return VLMResponse(
            text=text,
            structured_output=structured,
            model_id=self.model_id,
            runtime=self.runtime,
            execution_location=self.execution_location,
            prompt_tokens=None,
            generated_tokens=len(text.split()),
            time_to_first_token_ms=round(dt, 3),
            generation_latency_ms=round(dt, 3),
            total_latency_ms=round(dt, 3),
            memory_usage_mb=self._rss_mb(),
            warnings=[_MOCK_NOTE, *warnings],
        )

    def describe_image(self, image: ImageInput, prompt: str | None = None,
                       grounding: dict | None = None) -> VLMResponse:
        t0 = time.perf_counter()
        summary, objects = _summarize_grounding(grounding)
        # If a structured response was requested, emit valid schema JSON.
        if prompt and "JSON object matching this schema" in prompt:
            scene = SceneUnderstanding(
                summary=summary,
                environment="unknown (mock cannot infer environment without a real model)",
                important_objects=objects,
                uncertainties=["Generated by the mock backend from detector counts only."],
            )
            payload = scene.model_dump()
            return self._respond(json.dumps(payload), payload, t0, [])
        return self._respond(summary, None, t0, [])

    def answer_question(self, image: ImageInput, question: str,
                        grounding: dict | None = None) -> VLMResponse:
        t0 = time.perf_counter()
        summary, objects = _summarize_grounding(grounding)
        q = question.lower()
        if "how many" in q and objects:
            # answer counts honestly from grounding
            names = [o["class"] for o in (grounding or {}).get("detected_objects", [])]
            counts = Counter(names)
            target = next((name for name in counts if name in q), None)
            if target:
                text = f"The detector grounding indicates {counts[target]} {target}(s)."
            else:
                text = f"Detected objects: {', '.join(objects)}. Specify which to count."
        elif "indoor" in q or "outdoor" in q:
            text = ("The mock backend cannot determine indoor/outdoor from a single frame; "
                    "a real VLM is required.")
        else:
            text = (f"Based on detector grounding: {summary} "
                    "A real VLM is needed to reason further about this question.")
        return self._respond(text, None, t0, [])

    def analyze_video(self, frames: list[ImageInput], prompt: str,
                      grounding: dict | None = None) -> VLMResponse:
        t0 = time.perf_counter()
        summary, _ = _summarize_grounding(grounding)
        text = (f"Analyzed {len(frames)} frames. {summary} "
                "Temporal reasoning requires a real video-capable VLM.")
        return self._respond(text, None, t0, [])

    def unload(self) -> None:
        self._health = HealthState.UNKNOWN
